version: "3.7" # specify docker-compose version

# Define the services/containers to be run
services:

  database:
    image: kartoza/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_DBNAME=${DBNAME}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,pg_trgm
    ports:
      - 5432:5432
    restart: always

  redis:
    image: "redis"
    ports:
      - 6379:6379

  nest:
    build: .
    ports:
      - "3000:3000" #specify ports forewarding
    command:
      bash -c "while !</dev/tcp/database/5432; do sleep 1; done; npm install &&
      npm run typeorm:makemigrations 'init' && npm run typeorm:migrate && npm run build && npm run start"
    depends_on:
      - redis
      - database


volumes:
  postgres_data:
